ups_3/ups/urls.py
from django.urls import path
from django.conf.urls import url

from . import views

app_name = 'ups'
urlpatterns = [
    path('', views.PackageView.as_view(), name='index'),
    #path(r'signup/', views.signup, name='signup'),
    #path(r'tracking/', views.tracking, name='tracking'),
    path(r'searchPackage/', views.searchPackage, name='searchPackage'),
    path(r'world/', views.world, name='world'),
    #path(r'result/', views.result, name='result'),
    # The following are the web page that should be used internally
    # for communicating between the daemon and the database
    path(r'aRequestTruck/', views.aRequestTruck, name='aRequestTruck'),
    path(r'aRequestPackID/', views.aRequestPackID, name='aRequestPackID'),
    path(r'aAddProduct/', views.aAddProduct, name='aAddProduct'),
    path(r'aLoaded/', views.aLoaded, name='aLoaded'),
    path(r'aTruckToGo/', views.aTruckToGo, name='aTruckToGo'),
    path(r'aGetPackDes/', views.aGetPackDes, name='aGetPackDes'),
    path(r'wTruckCompletion/', views.wTruckCompletion, name='wTruckCompletion'),
    path(r'wPackageDelivered/', views.wPackageDelivered, name='wPackageDelivered'),

    url(r'^tracking/', views.tracking, name='tracking'),
    url(r'^usertracking/', views.usertracking, name='usertracking'),
    url(r'^signup/', views.signup, name='signup'),
    url(r'^login/', views.signin, name='signin'),
    url(r'^logout/', views.signout, name='signout'),
    url(r'^changeDes/', views.changeDes, name='changeDes'),
    url(r'^package_detail/', views.package_detail, name='package_detail'),
]

ups_3/ups_1/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    #path('account/', include('account.urls')),
    path('ups/', include('ups.urls')),
    path('admin/', admin.site.urls),
]

ups_3/ups/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

# All the info about the truck
class Truck(models.Model):
    truck_id = models.IntegerField(default=-1)
    posX = models.IntegerField(default=0)
    posY = models.IntegerField(default=0)
    warehouseID = models.IntegerField(default=-1)
    status = models.IntegerField(default=0)
    # 0=idle, 1=to_warehouse, 2=at_warehouse 3=delivery

# All the info about a package
class Package(models.Model):
    userID = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True)
    #details = models.CharField(max_length=200) # C
    destinationX = models.IntegerField(default=0)
    destinationY = models.IntegerField(default=0)
    whID = models.IntegerField(default=0)
    #quantity = models.IntegerField(default=0) # C
    deliveryStatus = models.IntegerField(default=0)
    # 0=created, 1=truck en route, 2=truck waiting, 3=out for delivery, 4=delivered

# All the info about a waiting warehouse call from Amazon
class Task(models.Model):
    whID = models.IntegerField(default=0)


# All the Details of a single item
class Product(models.Model):
    pack = models.ForeignKey(Package, on_delete=models.CASCADE)
    item_id = models.IntegerField(default=-1)
    description = models.CharField(max_length=500)
    quantity = models.IntegerField(default=0)

ups_3/ups/forms.py
from django import forms
from django.forms import ModelForm,modelformset_factory
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import *

class registerForm(UserCreationForm):
    username   = forms.CharField(max_length=100)
    password1  = forms.CharField(widget=forms.PasswordInput())
    password2  = forms.CharField(widget=forms.PasswordInput())
    email = forms.EmailField()
    class Meta:
        model = User
        fields = ('username','password1', 'password2','email')

        def __init__(self,*args, **kwargs):
            super(registerForm, self).__init__(*args, **kwargs)
            

ups_3/ups/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, JsonResponse
from django.views import generic
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.models import User
from copy import deepcopy
from django import forms
from .forms import *
from .models import *

import json

# Create your views here.
class UserForm(forms.Form):
    username = forms.CharField(label = 'username',max_length=100)
    email = forms.CharField(label = 'email',max_length=50)
    password = forms.CharField(label = 'password',max_length=50,widget=forms.PasswordInput())

class PackageView(generic.ListView):
    template_name = 'ups/index.html'
    context_object_name = 'packages_list'

    def get_queryset(self):
        return Package.objects.all()
# User Signup
def signup(request):
    if request.method == "POST":
        f = registerForm(request.POST)
        if f.is_valid():
            f.save()
            username = f.cleaned_data.get('username')
            filterResult = User.objects.filter(username = username)
            existing=[]
            if len(filterResult)>0:
                return render(request,'ups/signup.html',{'username already been taken':existing})
            else:
                password1 = f.cleaned_data.get('password1')
                password2 = f.cleaned_data.get('password2')
                errors = []
                if (password2 != password1):
                    errors.append("Password is not repeated correctly!")
                    return render(request, 'ups/signup.html',{'errors':errors})
                password = password2
                email = f.cleaned_data.get('email')
                user = User.objects.create(username=username,password=password1)
                user.save()
                userid = user.pk
                return render(request,'ups/usertracking.html', {'userid': userid})                       
    else:
        f = registerForm()
    return render(request, 'ups/signup.html', {'f': f})

def signin(request):
    if request.method == 'POST':
        uf = UserForm(request.POST)
        if uf.is_valid():
            username = uf.cleaned_data['username']
            password = uf.cleaned_data['password']
        username = request.POST['username']
        raw_password = request.POST['password']
        user = authenticate(username = username, password = raw_password)
        if user is not None:
            if user.is_active:
                login(request,user)
                return redirect('ups/tracking/')
            else:
                return render(request, 'ups/login.html',{'uf':uf, 'incorrect user':errors})
        else:
            return render(request,'ups/login.html',{'uf':uf, 'incorrect password':errors})
    else:
        uf = UserForm()
    return render(request,'ups/login.html',{'uf':uf})

@login_required
def signout(request):
    logout(request)
    return render(request,'ups/tracking.html')

@login_required
def changeDes(request):
    #package = Package.objects.get(package_id = pk)
    if request.method == "POST":
        if "package_id" in request.POST:
            pack_id = request.POST["package_id"]
        else:
            return render(request, 'ups/changeDes.html', {'errorMsg': 'The input package ID is invalid'})
        if "new_destination_X" in request.POST:
            new_destination_X = request.POST["new_destination_X"]
        else:
            return render(request, 'ups/changeDes.html', {'errorMsg': 'The input destination X is invalid'})
        if "new_destination_Y" in request.POST:
            new_destination_Y =request.POST["new_destination_Y"]
        else:
            return render(request, 'ups/changeDes.html', {'errorMsg': 'The input destination Y is invalid'})

        # Check if the package exists
        try:
            thePack = Package.objects.get(pk=pack_id)
        except Package.DoesNotExist:
            return render(request, 'ups/changeDes.html', {'errorMsg': 'The package does not exist'})

        # Check the user identity
        print("True Pack", thePack.userID.pk)
        print("I'm", request.user.id)
        if thePack.userID is None:
            return render(request, 'ups/changeDes.html', {'errorMsg': 'You are not authoized to change this package'})
        else:
            trueUserID = thePack.userID.pk
            currUser = request.user.id
            if trueUserID != trueUserID:
                return render(request, 'ups/changeDes.html', {'errorMsg': 'You are not authoized to change this package'})
        
        # Check the status of the package
        status = thePack.deliveryStatus
        if status !=3 and status != 4:
            thePack.destinationX = new_destination_X
            thePack.destinationY = new_destination_Y
            thePack.save()
            return render(request, 'ups/changeDes.html', {'errorMsg': 'Success!'})
        
        else:
            return render(request, 'ups/changeDes.html', {'errorMsg': 'The package is out for delivery'})
    else:
        return render(request, 'ups/changeDes.html')

def packStatus(deliveryStatus):
    if deliveryStatus == 0:
        return 'Created'
    elif deliveryStatus == 1:
        return 'Truck en route to warehouse'
    elif deliveryStatus == 2:
        return 'Waiting to be loaded at warehouse'
    elif deliveryStatus == 3:
        return 'Out for delivery'
    else:
        return 'Delivered'
    
@login_required
def package_detail(request):
    currUser = request.user
    allPacks = Package.objects.filter(userID=currUser)
    if len(allPacks) == 0:
        # There is no package associated with this user
        return render(request, 'ups/package_detail.html')
    else:
        # There is at least one package associated with the current user
        userPackages = []
        for pack in allPacks:
            currPack = deepcopy(pack)
            cond = packStatus(pack.deliveryStatus)
            currPack.condition = cond
            currPack.product = []
            prodInPack = Product.objects.filter(pack=pack)
            for prod in prodInPack:
                print(prod.description)
                theProd = deepcopy(prod)
                currPack.product.append(theProd)

            userPackages.append(currPack)
            
        return render(request, 'ups/package_detail.html', {'allPacks': userPackages})


def tracking(request):
    return render(request, 'ups/tracking.html')

@login_required
def usertracking(request):
    userid = request.user.id
    return render(request, 'ups/usertracking.html',{'userid': userid})

def searchPackage(request):
    if request.method == "POST":
        track_id = request.POST.get("tracking_id", -1)
        print("the tracking id is", track_id)
        try:
            selected_package = Package.objects.get(pk=request.POST['tracking_id'])
        except (KeyError, Package.DoesNotExist):
            return render(request, 'ups/tracking.html', {
                'error_message': "The package ID doesn't exist.",
            })
        
        return render(request, 'ups/tracking.html', {'pack_id': selected_package.pk,
                                                     'pack_status': packStatus(selected_package.deliveryStatus),})
        #else:
            #return HttpResponseRedirect(reverse('ups:index'))
    else:
        return render(request, 'ups/tracking.html')
        
    

@csrf_exempt
def aRequestTruck(request):
    if request.method == "POST":
        data = request.body.decode('utf-8')
        receivedData = json.loads(data)
        warehouse_id = receivedData["wh_id"]
        # Search Through all the trucks to see which one is available
        if Truck.objects.filter(status=0).exists():
            freeTruck = Truck.objects.filter(status=0)[0]
            freeTruck.status = 1
            freeTruck.warehouseID = warehouse_id
            freeTruck.save()
            print("The free truck is truckID", freeTruck.truck_id)
            # Change the stauts of all the pending packages at that warehouse to truck en route
            packages_set = Package.objects.filter(whID=warehouse_id, deliveryStatus=0)
            if packages_set.exists():
                for pack in packages_set:
                    print("Package ID ", pack.pk, " is at the warehouse", warehouse_id)
                    pack.deliveryStatus = 1
                    pack.save()
        
            return JsonResponse({'truck_id': freeTruck.truck_id})
        else:
            # There is no free truck. Put it on the Task Table
            newTask = Task(whID=warehouse_id)
            newTask.save()
            print("There is no free truck")
            return JsonResponse({'truck_id': -1})
    else:
        return HttpResponse("You are not authorized to view this page")
    
@csrf_exempt
def aRequestPackID(request):
    if request.method == "POST":
        data = request.body.decode('utf-8')
        receivedData = json.loads(data)
        user = receivedData["user"]
        #itemID = receivedData["itemID"]
        #itemDsp = receivedData["description"]
        #itemQuantity = receivedData["quantity"]    
        destination_x = receivedData["x"]
        destination_y = receivedData["y"]
        warehouse_id = receivedData["whID"]

        # Need to find out if the user is an input since it is optional
        if user == -1:
            # There is no user field
            newPackage = Package(destinationX=destination_x, destinationY=destination_y, whID=warehouse_id, deliveryStatus=0)
        else:
            # UserID is the User object, not just the user pk
            try:
                theUser = User.objects.get(pk=user)
            except User.DoesNotExist:
                # User doesn't exist, return an invalid packID
                return JsonResponse({"newID": -1})
            

ups_3/ups/templates/ups/base.html
<!DOCTYPE html>
<html>
  <head>
    <style>
      ul {
      list-style-type: none;
      margin: 0;
      padding: 0;
      }

      li {
      display: inline;
      }
    </style>
  </head>
  <body>
    <h1>Welcome to UPS!</h1>
    <ul>
      {% if user.is_authenticated %}
      <li><a href="{% url 'ups:usertracking' %}">User Tracking</a></li>
      <li><a href="{% url 'ups:package_detail' %}">Your Package</a></li>
      <li><a href="{% url 'ups:changeDes' %}">Redirect Package</a></li>
      <li><a href="{% url 'ups:signout' %}">Logout</a></li>
      {% else %}
      <li><a href="{% url 'ups:tracking' %}">Tracking</a></li>
      <li><a href="{% url 'ups:signin' %}">Login</a></li>
      <li><a href="{% url 'ups:signup' %}">Signup</a></li>
      {% endif %}
    </ul>

    {% block content %}
    <p id = "content">
    </p>
    {% endblock %}
    
  </body>
</html>

ups_3/ups/templates/ups/base1.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Welcome to UPS</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <style>
      * {
      box-sizing: border-box;
      font-family: Arial, Helvetica, sans-serif;
      }

      body {
      margin: 0;
      font-family: Arial, Helvetica, sans-serif;
      }

      /* Style the top navigation bar */
      .topnav {
      overflow: hidden;
      background-color: #333;
      }

      /* Style the topnav links */
      .topnav a {
      float: left;
      display: block;
      color: #f2f2f2;
      text-align: center;
      padding: 14px 16px;
      text-decoration: none;
      }

      /* Change color on hover */
      .topnav a:hover {
      background-color: #ddd;
      color: black;
      }

      /* Style the content */
      .content {
      background-color: #ddd;
      padding: 10px;
      height: 200px; /* Should be removed. Only for demonstration */
      }

      /* Style the footer */
      .footer {
      background-color: #f1f1f1;
      padding: 10px;
      }
    </style>
    <div class="topnav">
      {% if user.is_authenticated %}
      <a href="tracking">Tracking</a>
      <a href="package_detail">Your Package</a>
      <a href="changeDes">Redirect Package</a>
      {% else %}
      <a href="tracking">Tracking</a>
      <a href="login">Login</a>
      <a href="signup">Signup</a>
      {% endif %}
    </div>
  </head>
  <body>
    {% block content %}
    {% endblock %}
  </body>
</html>

ups_3/ups/templates/ups/changeDes.html
{% extends 'ups/base.html' %}

{% block content %}
<h1>Change Destination for Package</h1>
{% if errorMsg %}<p><strong>{{ errorMsg }}</strong></p>{% endif %}
<form action="{% url 'ups/changeDes' %'}" method="POST">
   {% csrf_token %}
   Package ID: <input type="number" name="package_id"><br>
   Destination_x: <input type="number" name="new_destination_X">
   Destination_y: <input type="number" name="new_destination_Y">
   <button type="submit">Change Package Destination</button>
</form>
{% endblock %}

ups_3/ups/templates/ups/index.html
{% if packages_list %}
<ul>
  {% for pack in packages_list %}
  <li>{{ pack.id }}</li>
  {% endfor %}
</ur>
{% else %}
<p>No package yet</p>
{% endif %}

ups_3/ups/templates/ups/login.html
{% extends 'ups/base.html' %}

{% block content %}
{% if errors %}
<div>
  <h3>{{ errors }}</h3>
</div>
{% endif %}
<h1>login</h1>
<form method="post" enctype="multipart/form-data">
  {% csrf_token %}
  {{uf.as_p}}
  <button type="submit">Log in</button>
</form>
{% endblock %}

ups_3/ups/templates/ups/package_detail.html
{% extends 'ups/base.html' %}

{% block content %}
{% if msg %}
<p>{{ msg }}</p>
{% else %}
<div id="detail" class="package_detail">
  {% for pack in allPacks %}
  <p>Package ID: {{ pack.id }}</p>
  <p>Package Destination X: {{ pack.destinationX }}</p>
  <p>Package Destination Y: {{ pack.destinationY }}</p>
  <p>Package Status: {{ pack.condition }}</p>
  {% for prod in pack.product %}
  <p>Item ID: {{ prod.item_id}}</p>
  <p>Item Description: {{ prod.description}}</p>
  <p>Item Quantity: {{ prod.quantity}}</p>
  {% endfor %}
  {% endfor %}
</div>
{% endif %}
{% endblock %}

ups_3/ups/templates/ups/signup.html
{% extends 'ups/base.html' %}
{% block content %}
<h1>Signup</h1>
<form action= "{% url 'ups:signup' %}" method="post" enctype="multipart/form-data">
  {% csrf_token %}
  {{f.as_p}}
  <input type="submit" value="ok"></input>
</form>
{% endblock %}

ups_3/ups/templates/ups/tracking.html
{% extends 'ups/base.html' %}
{% block content %}
{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
{% if pack_id %}
<p>Package ID: {{ pack_id }}</p>
<p>Package Status: {{ pack_status }}</p>
{% endif %}
<form action="{% url 'ups:searchPackage' %}" method="post">
  {% csrf_token %}
  <div class="search">
    <input type="number" class="search_key" name="tracking_id"/>
    <input type="submit" class="submit" value="Track"/>
  </div>
</form>

{% endblock %}

ups_3/ups/templates/ups/usertracking.html
{% extends 'ups/base.html' %}
{% block content %}
{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
{% if userid %}
<div>
  <h3>User ID: {{ userid }}</h3>
</div>
{% endif %}
{% if pack %}{{ pack.id }}{% endif %}
<form action="{% url 'ups:searchPackage' %}" method="post">
  {% csrf_token %}
  <div class="search">
    <input type="number" class="search_key" value="tracking_id"/>
    <input type="submit" class="submit" value="Track"/>
  </div>
</form>

{% endblock %}